# -*- coding: utf-8 -*-
"""assignment2.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GJcwF5uDIvfMeNbXs3XlB64ub9vhzCz

ANANYA V R

ASSIGNMENT 2

1. Create and Access Elements:

 Create a list of 5 fruits.

  Access the second and fourth fruit in the list and print them.
"""

fruits = ["apple", "banana", "cherry", "mango", "grape"]
print(fruits[1])
print(fruits[3])

"""2. Modify a List:

 Add a new fruit to the list.

 Replace the third fruit in the list with "Strawberry."

 Remove the last fruit from the list.
"""

fruits = ["apple", "banana", "cherry", "mango", "grape"]
print(fruits[1])
print(fruits[3])
fruits.append("orange")
fruits[2] = "Strawberry"
fruits.pop()
print(fruits)
del fruits[4]
print(fruits)

"""3. List Methods:

Sort the list alphabetically.

Reverse the order of the list.

Count how many times "Apple" appears in the list (add "Apple" if necessary).
"""

fruits = ["apple", "banana", "cherry", "mango", "grape"]
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)
fruits.append("apple")
print(fruits.count("apple"))

"""Part 2: Tuples
1. Create and Access Elements:

 Create a tuple with 5 numbers: 10, 20, 30, 40, 50.

 Print the first and last number in the tuple.
"""

num=(10,20,30,40,50)
print(num[0])
print(num[-1])

"""2. Immutable Nature of Tuples:

 Try changing the second number in the tuple to 25. Observe and note down the
error message.
"""

num=(10,20,30,40,50)
num[1]=25
print(num)

"""3. Tuple Operations:

 Use tuple unpacking to assign the values of the tuple to 5 different variables. Print
each variable.
"""

num = (10, 20, 30, 40, 50)
a, b, c, d, e = num
print("a",a)
print("b",b)
print("c",c)
print("d",d)
print("e",e)

"""Part3:Dictionaries
1. Create and Access Elements:
 Create a dictionary that stores information about a student:
 Name: "John"
 Age: 20
 Subjects: ["Math", "Physics", "Chemistry"]
 Access the student's age and print it.
"""

dict = {"Name": "John","Age": 20,"Subjects": ["Math", "Physics", "Chemistry"]}
print(dict["Age"])

"""2.Modify the Dictionary:

 Add a new key-value pair for "Grade" with the value "A".

 Change the student's age to 21.

 Remove the "Subjects" key from the dictionary.
"""

dict = {"Name": "John","Age": 20,"Subjects": ["Math", "Physics", "Chemistry"]}
dict["Grade"] = "A"
dict["Age"] = 21
del dict["Subjects"]
print(dict)

"""3. Dictionary Methods:

 Print all the keys in the dictionary.

 Print all the values in the dictionary.
"""

dict = {"Name": "John","Age": 20,"Subjects": ["Math", "Physics", "Chemistry"]}
print(dict.keys())
print(dict.values())